TALLER

In [1]:
pip install wooldridge

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 12.9 MB/s eta 0:00:00


In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
import wooldridge as wd

In [21]:
wage = wd.data('wage1')[['wage', 'educ', 'exper']]
wage

wage  educ  exper
0     3.10    11      2
1     3.24    12     22
2     3.00    11      2
3     6.00     8     44
4     5.30    12      7
..     ...   ...    ...
521  15.00    16     14
522   2.27    10      2
523   4.67    15     13
524  11.56    16      5
525   3.50    14      5

[526 rows x 3 columns]

In [23]:
y = wage['wage'].to_numpy()
x = wage [['educ', 'exper']].to_numpy()

In [26]:
x

array([[11,  2],
       [12, 22],
       [11,  2],
       ...,
       [15, 13],
       [16,  5],
       [14,  5]])

In [ ]:
y

In [28]:
X = np.c_[np.ones(len(x)), x]
X

array([[ 1., 11.,  2.],
       [ 1., 12., 22.],
       [ 1., 11.,  2.],
       ...,
       [ 1., 15., 13.],
       [ 1., 16.,  5.],
       [ 1., 14.,  5.]])

In [29]:
X.T.dot(X)

array([[   526.,   6608.,   8951.],
       [  6608.,  87040., 106539.],
       [  8951., 106539., 249027.]])

In [30]:
betas = np.linalg.inv(X.T.dot(X))

In [31]:
betas = np.linalg.inv(X.T.dot(X)).dot(X.T.dot(y))

In [32]:
betas

array([-3.39053946,  0.64427208,  0.0700954 ])

In [59]:
# y estimado
y_estimado = X.dot(betas)

In [60]:
# error estimado
u_estimado = y-y_estimado

In [61]:
numerador=sum(u_estimado**2)

In [52]:
n,k=X.shape

In [64]:
# sigma
sigma = numerador/(n-k)

In [65]:
np.sqrt(sigma*np.linalg.inv(X.T.dot(X)))

<ipython-input-65-2616fb408987>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(sigma*np.linalg.inv(X.T.dot(X)))


array([[0.76656609,        nan,        nan],
       [       nan, 0.05380607, 0.01330144],
       [       nan, 0.01330144, 0.01097764]])

In [69]:
#error estandar
error_stand=np.diag(np.sqrt(sigma*np.linalg.inv(X.T.dot(X))))

<ipython-input-69-87a4b2a3c722>:1: RuntimeWarning: invalid value encountered in sqrt
  error_stand=np.diag(np.sqrt(sigma*np.linalg.inv(X.T.dot(X))))


In [72]:
# t
t = betas/error_stand

In [76]:
# Interbalos de Confianza
betas + 1.96 + error_stand

array([-0.66397337,  2.65807815,  2.04107303])

In [77]:
betas - 1.96 + error_stand

array([-4.58397337, -1.26192185, -1.87892697])

Los tres son estadisticamente significativos puesto que estos no pasan por cero (0)